version: '3'
services:
  app:
    restart: always
    build: ./docker/python
    working_dir: '/root/src'
    tty: true
    volumes:
      - .:/root/src
    ports:
      - 8002:8000
    environment:
      - PORT=8002